# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v2

      - name: Install portaudio
        run: |
          sudo apt-get update
          sudo apt-get install portaudio19-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip3 install -r requirements.txt -r requirements-dev.txt

      - name: Install package
        run: python3 setup.py install

      - name: Lint
        run: make lint

      - name: Unittest
        run: make unittest
